name: flutter_tuner
description: "A new Flutter plugin project."
version: 2.0.0
homepage:

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: com.degastonapps.flutter_tuner
        pluginClass: FlutterTunerPlugin
      ios:
        pluginClass: FlutterTunerPlugin
      #   sharedDarwinSource: true
      # macos:
      #   pluginClass: FlutterTunerPlugin
      #   sharedDarwinSource: true
